project:
  type: website

website:
  title: "Ann Wells, Ph.D. | Open Science | Data Science | Lupus Researcher"
  google-analytics: "G-41BY0H900V"
  page-navigation: true
  back-to-top-navigation: true
  page-footer: 
    center: |
      <br>
      Copyright &copy; 2024 Ann Wells, Ph.D.<br>

  navbar:
    foreground: "white"
    logo: "images/Ann.png"
    title: false
    pinned: false
    left:
    - text: "Welcome"
      href: index.qmd
    - text: "Publications"
      href: publications.qmd
    - text: "Open Science"
      href: open-science.qmd
    
    right:
    - icon: <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--!Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M294.8 188.2h-45.9V342h47.5c67.6 0 83.1-51.3 83.1-76.9 0-41.6-26.5-76.9-84.7-76.9zM256 8C119 8 8 119 8 256s111 248 248 248 248-111 248-248S393 8 256 8zm-80.8 360.8h-29.8v-207.5h29.8zm-14.9-231.1a19.6 19.6 0 1 1 19.6-19.6 19.6 19.6 0 0 1 -19.6 19.6zM300 369h-81V161.3h80.6c76.7 0 110.4 54.8 110.4 103.9C410 318.4 368.4 369 300 369z"/></svg>
      href: https://orcid.org/0000-0002-9720-0038
    - icon: github
      href: https://github.com/annwells/
    - icon: linkedin
      href: https://www.linkedin.com/in/annwellsphd/
    - icon: send
      href: mailto:ann.wells@jax.org
    - text: "CV"
      href: CV-Ann-2024.pdf

format:
  html:
    theme: pulse
    css: styles.css
    toc: true
    page-layout: full
    date-format: "MM DD YYYY"

editor: visual

