project:
  type: website

website:
  title: "Ann Wells, Ph.D. | Open Science | Data Science | Lupus Researcher"
  google-analytics: "G-41BY0H900V"
  page-navigation: true
  back-to-top-navigation: true
  page-footer: 
    center: |
      <br>
      Copyright &copy; 2024 Ann Wells, Ph.D.<br>
    
  navbar:
    foreground: "white"
    logo: "images/Ann.png"
    title: false
    pinned: false
    left:
    - text: "Welcome"
      href: index.qmd
    - text: "Publications"
      href: publications.qmd
    - text: "Open Science"
      href: open-science.qmd
    
    right:
    - icon: file-earmark-fill
      href: https://orcid.org/0000-0002-9720-0038
    - icon: github
      href: https://github.com/annwells/
    - icon: linkedin
      href: https://www.linkedin.com/in/annwellsphd/
    - icon: send
      href: mailto:ann.wells@jax.org
    - text: "CV"
      href: CV-Ann-2024.pdf

format:
  html:
    theme: pulse
    css: styles.css
    toc: true
    page-layout: full
    date-format: "MM DD YYYY"
    header-includes:
      - <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css">

editor: visual

